# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          apt-get update
          apt-get install tree
          tree
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Obungi AI Container Registry'
        repository: 'mycompanycopilot'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest